//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock
    {
        public int Stock_ID { get; set; }
        public Nullable<int> Prod_ID { get; set; }
        public string Prod_Name { get; set; }
        public Nullable<int> Cus_ID { get; set; }
        public Nullable<int> Supplier_ID { get; set; }
        public string Sup_Name { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> Stock_In { get; set; }
        public Nullable<int> Stock_Out { get; set; }
        public Nullable<int> Order_ID { get; set; }
        public Nullable<int> Order_Line_ID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Order Order { get; set; }
        public virtual Order_Line Order_Line { get; set; }
        public virtual Product Product { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
