//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier_Prod
    {
        public int Supplier_Prod_ID { get; set; }
        public Nullable<int> Supplier_ID { get; set; }
        public Nullable<int> Product_ID { get; set; }
        public string Sup_Name { get; set; }
        public Nullable<decimal> Sup_Price { get; set; }
        public Nullable<int> Supplier_Quantity { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
